" fzf installed via brew
set rtp+=$HOMEBREW_PREFIX/opt/fzf

" general
set ts=2 et shiftwidth=2  " 2-space soft tabs
set backspace=indent,eol,start " backspace over anything in insert mode
set shell=/bin/zsh
set encoding=utf-8
set clipboard=unnamed     " yank/paste uses system clipboard
set nofoldenable          " disable folding
set ignorecase smartcase  " case-insensitive unless uppercase used

set history=200		" keep 200 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set wildmenu		" command-line completion with Tab

set ttimeout		" time out for key codes
set ttimeoutlen=10	" minimal delay after Esc (reduces insert mode lag)

set scrolloff=5		" keep 5 lines visible above/below cursor
set splitbelow splitright " new splits open below and to the right

" persist undo history across file closes
set undofile
set undodir=~/.vim/undo

" vim bug, :terminal doesn't restore cursor. have to explicitly set
set t_SH=4

" I use "ex:" as shorthand for "example:"
" vim modelines thinks that's ex-mode
" ex: vim --clean <(echo "[ ex: ]")
set nomodeline

" Show @@@ in the last line if it is truncated.
set display=truncate

" colors
set hls
set is
"set cc=80
colors dracula

" Switch syntax highlighting on when the terminal has colors or when using the
" GUI (which always has colors).
if &t_Co > 2 || has("gui_running")
  syntax on
  hi Search ctermfg=46 ctermbg=0 cterm=underline
  hi Visual ctermbg=236
endif

" Do incremental searching when it's possible to timeout.
if has('reltime')
  set incsearch
  hi IncSearch ctermfg=46 ctermbg=0 cterm=underline
endif

" show search counts
set shortmess-=S

" Enable file type detection.
filetype plugin on

augroup vimStartup
  au!

  " When editing a file, always jump to the last known cursor position.
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
    \ |   exe "normal! g`\""
    \ | endif

  " Strip trailing whitespace on write
  autocmd BufWritePre * %s/\s\+$//e

augroup END

" Load plugins
call plug#begin('~/.vim/plug')
  Plug 'fatih/vim-go', { 'for': 'go' }
  Plug 'junegunn/fzf.vim'
  Plug 'tpope/vim-fugitive'
  Plug 'dense-analysis/ale'
  Plug '~/side/vimwiki'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'
  Plug 'hashivim/vim-terraform'
  Plug 'github/copilot.vim'
  Plug 'ludovicchabant/vim-gutentags'
call plug#end()

filetype indent off

" sourcing
for f in ["maps", "funcs"]
  exec "so $HOME/.vim/".f.".vim"
endfor

if $DOTPROFILE == "intuit"
  so $HOME/.vim/intuit.vim
endif

if $DOTPROFILE == "personal"
  so $HOME/.vim/personal.vim
endif
