set nocompatible

" rtp
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=/usr/local/opt/fzf

" vundle
filetype plugin indent off
  call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'dracula/vim'
    Plugin 'fatih/vim-go'
    Plugin 'junegunn/fzf.vim'
    Plugin 'scrooloose/nerdtree'
    Plugin 'vimwiki/vimwiki'
    Plugin 'tpope/vim-fugitive'
    Plugin 'godlygeek/csapprox'
    Plugin 'w0rp/ale'
  call vundle#end()
filetype plugin indent on

" general
set ts=2 et shiftwidth=2 sts=2
set bs=indent,eol,start
set sh=/bin/bash
set enc=utf-8
set nofoldenable
set clipboard=unnamed
set foldmethod=indent
set history=1000

" remove trailing spaces & save views
augroup AutoSaveViews
  autocmd!
  autocmd BufWritePre *.* %s/\s\+$//e
  autocmd BufWinLeave *.* mkview
  autocmd BufWinEnter *.* silent loadview
augroup END

" colors
syntax enable
set hls
set is
"set cc=80
colors dracula
hi Search ctermfg=46 ctermbg=0 cterm=underline
hi IncSearch ctermfg=46 ctermbg=0 cterm=underline
hi Visual ctermbg=236
set display+=lastline

" source maps
so $HOME/.vim/maps.vim

" source funcs
so $HOME/.vim/funcs.vim

" source mc configs
so $HOME/.vim/mc.vim

" source vimwiki configs
so $HOME/.vim/wiki.vim
