# Shell
brew "fzf"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Editor
brew "vim"

# Git
brew "gh"
brew "git-delta"

# CLI tools
brew "aspell"
brew "bat"
brew "ctags"
brew "eza"
brew "fd"
brew "gnu-sed"
brew "hey"
brew "jq"
brew "parallel"
brew "ripgrep"
brew "telnet"
brew "tree"
brew "watch"
brew "xh"
brew "yq"
brew "zoxide"

# Kubernetes
brew "k9s"
brew "kubectl"
brew "stern"

# Casks
cask "google-cloud-sdk"
