confs=(
  vars # should come first
  aliases
  opts
  funcs
)

export DOT="$HOME/.dot"
[[ $USER == jmoriarty ]] && export DOTPROFILE=intuit || export DOTPROFILE=personal

for conf ($confs); do
  source "$DOT/zsh/$conf.zsh";
done
