# $HOME/.zshenv will be sourced first, and for all sessions.
# For interactive sessions, /etc/zshrc and then this file
# will also be sourced.
#
# Only needed for interactive zsh should be here.

confs=(
  binds # should come first
  completion
  extra
  git
  hist
  theme # should come last
)

for conf ($confs); do
  source "$DOT/zsh/$conf.zsh";
done

autoload -U compinit
compinit
