plugins=(
  brew
  #git
  #docker
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

confs=(
  init #must come first
  aliases
  extra
  funcs
  git
  hist
  theme # must come last
)

for conf ($confs); do
  source "$DOT/zsh/$conf.zsh";
done
